/*
Copyright © 2026 Chad Glazier <chadglazier@outlook.com>
*/
package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Chad-Glazier/game-of-the-amazons-ai/scripts/bitboard"
	"github.com/spf13/cobra"
)

// bitboardsCmd represents the moves command
var bitboardsCmd = &cobra.Command{
	Use:   "bitboards <output_dir>",
	Short: "Generates the bitboards for efficient Amazons calculations",
	Args: cobra.MinimumNArgs(1),
	Long: `Generates a file in the specified directory named "P.java" (for
"precomputed") which has hard-coded Java matrices storing 
bitboards useful in various amazons movement/distance 
calculations.`,
	Run: func(cmd *cobra.Command, args []string) {
		outputDir := args[0];

		_, err := os.Stat(outputDir)
		if os.IsNotExist(err) {
			fmt.Printf(
				"Specified output directory \"%s\" does not exist.", 
				outputDir,
			)
			return
		}
		if err != nil {
			panic(err)
		}

		outputPath := filepath.Join(outputDir, "P.java")
		w, err := os.OpenFile(
			outputPath, 
			os.O_CREATE | os.O_WRONLY | os.O_TRUNC, 
			0644,
		)
		if err != nil {
			panic(err)
		}
		defer w.Close()

		writeMoves(w)
	},
}

func init() {
	rootCmd.AddCommand(bitboardsCmd)
}

func writeMoves(w io.Writer) {
	w.Write([]byte (header))
	defer w.Write([]byte (footer))

	writeRayBoards(w)
	writeSquareBoards(w)
}

var header = `//
// This is a generated file. See "scripts/README.md" for more information.
//
package ubc.cosc322.bitboard;

/**
 * This class stores precomputed (abbreviated to "P" for convenience) 
 * bitboards. 
 *
 * The bitboards were generated by the script in "scripts/", see the README
 * in that directory for more information.
 */
public class P {
	/* Represents the "North" direction; i.e., lesser row indices. */
	public static final byte N = 0;
	/* Represents the "Northeast" direction. */ 
	public static final byte NE = 1;
	/* Represents the "East" direction; i.e., greater column indices. */
	public static final byte E = 2;
	/* Represents the "Southeast" direction. */
	public static final byte SE = 3;
	/* Represnts the "South" direction; i.e., greater row indices. */
	public static final byte S = 4;
	/* Represents the "Southwest" direction. */
	public static final byte SW = 5;
	/* Represents the "West" direction; i.e., lesser column indices. */
	public static final byte W = 6;
	/* Represents the "Northwest" direction. */
	public static final byte NW = 7;

`
var footer = `
}
`


func writeRayBoards(w io.Writer) {
	const (
		N int = iota
		NE
		E 
		SE 
		S 
		SW
		W
		NW
	)

	w.Write([]byte(`
	/**
	 * A matrix that stores the bitboards that represent rays a queen can
	 * move along based on (1) the starting position index and (2) the 
	 * direction of the move. E.g., to get the move bitboard for a queen at 
	 * position 32 moving North, you would access:
	 *
	 * <pre>{@code
	 * long[] ray = P.ray[32][P.N];
	 * }</pre>
	 */
	public static final long[][][] ray = {` + "\n"))

	for row := range 10 {
		for col := range 10 {
			fmt.Fprintf(w, "\t\t{\n")
			for dir := range NW + 1 {
				fmt.Fprintf(w, "\t\t\t")
				bitboard.Write(w, bitboard.Ray(row, col, dir))
				fmt.Fprintf(w, ",\n")
			}
			fmt.Fprintf(w, "\t\t},\n")
		}
	}

	fmt.Fprintf(w, "\t};\n")
}

func writeSquareBoards(w io.Writer) {
	const (
		N int = iota
		NE
		E 
		SE 
		S 
		SW
		W
		NW
	)

	w.Write([]byte(`
	/**
	 * Stores bitboards that have only a single square flagged; the indexed
	 * position. E.g., if you want a bitboard with only a single flag at the
	 * position index 12, you would use
	 *
	 * <pre>{@code
	 * long[] square = P.square[12];
	 * }</pre>
	 */
	public static final long[][] square = {` + "\n"))

	for row := range 10 {
		for col := range 10 {
			fmt.Fprintf(w, "\t\t")
			bitboard.Write(w, bitboard.Square(row, col))
			fmt.Fprintf(w, ",\n")
		}
	}

	fmt.Fprintf(w, "\t};\n")
}
